### ISSUE TITLE
Assessment Results

### ISSUE THREAD

**Issue by rwarbelow** [baldm0mma/mod_0_skills#1]
# Checklist/Rubric

#### Part I: Creating Directories and Files; Initializing Git and Pushing to GitHub
* [x]  Directories are named correctly.
* [x]  Files are named correctly.
* [x]  Files and directories are structured correctly.
* [x]  Initial commit was made.
* [x]  Initial commit was pushed to GitHub.

#### Part II: Top Down Design
* [x]  Larger processes were broken into smaller layers.
* [x]  Changes were added and committed with a properly formatted commit message starting with a verb and a capital letter.
> Format looks good. Try to be more specific with your message. For example: `Break down process of ordering food` instead of `Add text to file`.
* [x]  Changes were pushed to Github.

#### Part III: Classes in a System
* [x]  Directories and files were named and structured correctly.
* [x]  The attributes chosen for **Class #1** represent states or characteristics.
* [x]  The attributes chosen for **Class #2** represent states or characteristics.
* [x]  The attributes chosen for **Class #3** represent states or characteristics.
> For things like `current_#_of_products`, even though it seems like a characteristic, it's more of a calculation (which would be a method). What I might do is include an attribute of `products` as an array, then a method `product_count` (or `count_products`) that evaluates how many items are in the `products` array at any given time since that may change with your `add_new_product` or `remove_item` methods. 
* [x]  The methods chosen for **Class #1** represent behaviors or actions.
* [x]  The methods chosen for **Class #2** represent behaviors or actions.
* [x]  The methods chosen for **Class #3** represent behaviors or actions.
* [x]  Data type (string, integer, boolean, array, hash/object, datetime) were identified for each attribute in all three classes.
* [ ]  Individual changes were added and committed separately with a properly formatted commit message.
> Your message looks great. In the rubric, it refers to `...committed each set of changes separately...`. It looks like there was one commit made for all three files.
* [x]  Changes were pushed to Github.

**Mod 0 Technical Assessment Results**

* [x]   Technical Ready
* [ ]   Pending
* [ ]   Not Ready
